### PR TITLE
fix: back handler in hike details not in the right place

### PR DESCRIPTION
**Pull request by rBergCode**
# Summary
This pull request includes changes to the `HikeDetailScreen` in the `HikeDetailsScreen.kt` file to improve the handling of the back button functionality.

Back button handling improvements:
Moving it to the correct place to have it work in all cases.

### CODE REVIEW

**Review by MaelImhof — COMMENTED** [review]
Simple and quick fix, thanks! How necessary do you think a regression test would be? I think it [is possible](https://stackoverflow.com/questions/72973956/jetpack-compose-back-button-press-in-automation-test) to trigger a system back button event in the tests.

**Comment by rBergCode** [comment]
I don't think it's relevant here. It's just an implementation error and we don't test it anywhere else

**Comment by MaelImhof** [comment]
True, no need for a regression test, however there are conflicts to be resolved before this can be merged.

**Review by MaelImhof — APPROVED** [review]
LGTM, thanks for the merge 👌🏻

**Pull request merged**
